// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef FOLDERADDEDOBJECT_H
#define FOLDERADDEDOBJECT_H

#include "MAPISchema.h"

namespace graphql::mapi::object {

class FolderAdded
	: public service::Object
{
protected:
	explicit FolderAdded();

public:
	virtual service::FieldResult<response::IntType> getIndex(service::FieldParams&& params) const = 0;
	virtual service::FieldResult<std::shared_ptr<Folder>> getAdded(service::FieldParams&& params) const = 0;

private:
	std::future<service::ResolverResult> resolveIndex(service::ResolverParams&& params);
	std::future<service::ResolverResult> resolveAdded(service::ResolverParams&& params);

	std::future<service::ResolverResult> resolve_typename(service::ResolverParams&& params);
};

} // namespace graphql::mapi::object

#endif // FOLDERADDEDOBJECT_H
