// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef ITEMSRELOADEDOBJECT_H
#define ITEMSRELOADEDOBJECT_H

#include "MAPISchema.h"

namespace graphql::mapi::object {

class ItemsReloaded
	: public service::Object
{
protected:
	explicit ItemsReloaded();

public:
	virtual service::FieldResult<std::vector<std::shared_ptr<Item>>> getReloaded(service::FieldParams&& params) const = 0;

private:
	std::future<service::ResolverResult> resolveReloaded(service::ResolverParams&& params);

	std::future<service::ResolverResult> resolve_typename(service::ResolverParams&& params);
};

} // namespace graphql::mapi::object

#endif // ITEMSRELOADEDOBJECT_H
