// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef ITEMREMOVEDOBJECT_H
#define ITEMREMOVEDOBJECT_H

#include "MAPISchema.h"

namespace graphql::mapi::object {

class ItemRemoved
	: public service::Object
{
protected:
	explicit ItemRemoved();

public:
	virtual service::FieldResult<response::IntType> getIndex(service::FieldParams&& params) const = 0;
	virtual service::FieldResult<response::IdType> getRemoved(service::FieldParams&& params) const = 0;

private:
	std::future<service::ResolverResult> resolveIndex(service::ResolverParams&& params);
	std::future<service::ResolverResult> resolveRemoved(service::ResolverParams&& params);

	std::future<service::ResolverResult> resolve_typename(service::ResolverParams&& params);
};

} /* namespace graphql::mapi::object */

#endif // ITEMREMOVEDOBJECT_H
