// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef MAPIOBJECTS_H
#define MAPIOBJECTS_H

#include "MAPISchema.h"

#include "QueryObject.h"
#include "MutationObject.h"
#include "SubscriptionObject.h"
#include "StoreObject.h"
#include "FolderObject.h"
#include "ItemObject.h"
#include "FileAttachmentObject.h"
#include "ConversationObject.h"
#include "IntIdObject.h"
#include "StringIdObject.h"
#include "NamedIdObject.h"
#include "IntValueObject.h"
#include "BoolValueObject.h"
#include "StringValueObject.h"
#include "GuidValueObject.h"
#include "DateTimeValueObject.h"
#include "BinaryValueObject.h"
#include "StreamValueObject.h"
#include "PropertyObject.h"
#include "ItemAddedObject.h"
#include "ItemUpdatedObject.h"
#include "ItemRemovedObject.h"
#include "ItemsReloadedObject.h"
#include "FolderAddedObject.h"
#include "FolderUpdatedObject.h"
#include "FolderRemovedObject.h"
#include "FoldersReloadedObject.h"

#endif // MAPIOBJECTS_H
