// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef STRINGIDOBJECT_H
#define STRINGIDOBJECT_H

#include "MAPISchema.h"

namespace graphql::mapi::object {

class StringId
	: public service::Object
{
protected:
	explicit StringId();

public:
	virtual service::FieldResult<response::StringType> getName(service::FieldParams&& params) const = 0;

private:
	std::future<service::ResolverResult> resolveName(service::ResolverParams&& params);

	std::future<service::ResolverResult> resolve_typename(service::ResolverParams&& params);
};

} // namespace graphql::mapi::object

#endif // STRINGIDOBJECT_H
