name: Windows

on: [push, pull_request]

jobs:
  vs2022:
    strategy:
      fail-fast: false
      matrix:
        arch: ['x86', 'x64']
        libs: ['shared', 'static']
        config: ['Debug', 'Release']

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set target triplet
      id: set-variables
      shell: pwsh
      run: echo "vcpkg_triplet=${{ matrix.arch }}-windows$(if ('${{ matrix.libs }}' -eq 'static') { '-static' })" >> $env:GITHUB_OUTPUT

    - name: Cache vcpkg
      uses: actions/cache@v3
      id: cache-vcpkg
      with:
        path: build/vcpkg_cache/
        key: vcpkg-binaries-${{ steps.set-variables.outputs.vcpkg_triplet }}

    - name: Create Build Environment
      if: ${{ !steps.cache-vcpkg.outputs.cache-hit }}
      run: |
        cmake -E make_directory build
        cmake -E make_directory build/vcpkg_cache

    - name: Configure
      shell: pwsh
      working-directory: build/
      run: |
        $vcpkgToolchain = Join-Path $env:VCPKG_INSTALLATION_ROOT '.\scripts\buildsystems\vcpkg.cmake' -Resolve
        $vcpkgTriplet = '${{ steps.set-variables.outputs.vcpkg_triplet }}'
        $cmakeSharedLibs = $(if ('${{ matrix.libs }}' -eq 'shared') { 'ON' } else { 'OFF' })
        $msbuildArch = $(if ('${{ matrix.arch }}' -eq 'x64') { 'X64' } else { 'Win32' })

        $cachedBinaries = Join-Path $(Get-Location) './vcpkg_cache/' -Resolve
        $cacheAccess = $(if ('${{ steps.cache-vcpkg.outputs.cache-hit }}' -eq 'true') { 'read' } else { 'write' })
        $env:VCPKG_BINARY_SOURCES = "clear;files,$cachedBinaries,$cacheAccess"

        cmake "-DCMAKE_TOOLCHAIN_FILE=$vcpkgToolchain" "-DVCPKG_TARGET_TRIPLET=$vcpkgTriplet" "-DBUILD_SHARED_LIBS=$cmakeSharedLibs" -G "Visual Studio 17 2022" -A "$msbuildArch" ${{ github.workspace }}

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{ matrix.config }} -j -v

    - name: Test
      working-directory: build/
      run: ctest -C ${{ matrix.config }} --output-on-failure
